<?xml version="1.0" encoding="utf-8"?><Database Name="Electronic_Shop" Class="DBShopDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="WebSettings" ConnectionString="Data Source=DESKTOP-HCB194V\SQLEXPRESS;Initial Catalog=Electronic_Shop;Integrated Security=True" SettingsObjectName="System.Configuration.ConfigurationManager.ConnectionStrings" SettingsPropertyName="Electronic_ShopConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.Product" Member="Products">
    <Type Name="Product">
      <Column Name="ID" Type="System.Int64" DbType="BigInt NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="NVarChar(250)" CanBeNull="true" />
      <Column Name="ShortName" Type="System.String" DbType="VarChar(250)" CanBeNull="true" />
      <Column Name="Description" Type="System.String" DbType="NVarChar(500)" CanBeNull="true" />
      <Column Name="Image" Type="System.String" DbType="NVarChar(250)" CanBeNull="true" />
      <Column Name="MoreImages" Type="System.Xml.Linq.XElement" DbType="Xml" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="Price" Type="System.Decimal" DbType="Decimal(18,0)" CanBeNull="true" />
      <Column Name="PromotionPrice" Type="System.Decimal" DbType="Decimal(18,0)" CanBeNull="true" />
      <Column Name="IncludedVAT" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="Quantity" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="CategoryID" Type="System.Int64" DbType="BigInt" CanBeNull="true" />
      <Column Name="Detail" Type="System.String" DbType="NText" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="Warranty" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="CreatedDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="CreatedBy" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="ModifiedDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="ModifiedBy" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Status" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="TopHot" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="[View]" Member="View" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </Type>
  </Table>
</Database>